name: Upload APK to Google Drive

on:
  push:
    branches:
      - main  # Workflow startet nur bei Push auf main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 googleapiclient

      - name: Decode and Save client_secret.json
        run: |
          echo "${{ secrets.GOOGLE_CLIENT_SECRET_BASE64 }}" | base64 --decode > client_secret.json

      - name: Upload File to Google Drive
        env:
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: |
          import os
          from google.oauth2.credentials import Credentials
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaFileUpload

          # 🔹 API Credentials aus Secrets abrufen
          CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
          CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
          REFRESH_TOKEN = os.getenv("GOOGLE_REFRESH_TOKEN")
          FOLDER_ID = os.getenv("GOOGLE_DRIVE_FOLDER_ID")

          # 🔹 Dateiname aus Repository bestimmen
          FILE_NAME = "app-release.apk"  # Standardname
          BRANCH_NAME = os.getenv("GITHUB_REF_NAME", "main")  # Branch-Name
          NEW_FILE_NAME = f"PROJECT-1.0.0_{BRANCH_NAME}-{FILE_NAME}"  # Angepasster Dateiname

          # 🔹 Authentifizierung mit OAuth2 Refresh Token
          creds = Credentials(
              None,
              refresh_token=REFRESH_TOKEN,
              client_id=CLIENT_ID,
              client_secret=CLIENT_SECRET,
              token_uri="https://oauth2.googleapis.com/token"
          )

          # 🔹 Google Drive API aufbauen
          service = build("drive", "v3", credentials=creds)

          # 🔹 Datei-Metadaten festlegen
          file_metadata = {"name": NEW_FILE_NAME}
          if FOLDER_ID:
              file_metadata["parents"] = [FOLDER_ID]

          # 🔹 Datei hochladen mit MediaFileUpload
          media = MediaFileUpload(FILE_NAME, mimetype="application/vnd.android.package-archive", resumable=True)
          file = service.files().create(body=file_metadata, media_body=media, fields="id").execute()

          print(f"✅ Datei erfolgreich hochgeladen: {file.get('id')}")
