name: Rename File Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch auswählen"
        required: true
        default: "master"
      version:
        description: "Version des Projekts"
        required: true
        default: "3.3.0.0"

jobs:
  rename-file:
    runs-on: ubuntu-latest
    steps:
      - name: Beispiel: Datei erstellen (Simulation)
        run: echo "Test APK-Datei" > app-full-release-unsigned-signed.apk

      - name: Datei umbenennen
        run: |
          project_name="PROJECT"
          version=${{ github.event.inputs.version }}
          branch=${{ github.event.inputs.branch }}
          original_file="app-full-release-unsigned-signed.apk"
          new_file="${project_name}-${version}_${branch}-app-full-release.apk"

          if [ -f "$original_file" ]; then
            mv "$original_file" "$new_file"
            echo "Datei wurde umbenannt in: $new_file"
          else
            echo "Originaldatei nicht gefunden: $original_file"
            exit 1
          fi

      - name: Dateien auflisten
        run: ls -l
